export const ADD_USER = 'ADD_USER';
export const USER_EXISTS = 'USER_EXISTS';
export const USER_REGISTERED = 'USER_REGISTERED';
export const USER_NOT_REGISTERED = 'USER_NOT_REGISTERED';
export const INVALID_LOGIN = 'INVALID_LOGIN';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const SET_LOGGED_OUT = 'SET_LOGGED_OUT';
