export const SET_BASIC_CONTENT = 'SET_BASIC_CONTENT';
export const CHANGE_COUNT_OF_LIKES = 'CHANGE_COUNT_OF_LIKES';
export const CHANGE_COUNT_OF_STARS = 'CHANGE_COUNT_OF_STARS';
export const FILTER_MOVIE = 'FILTER_MOVIE';
export const SORT_BY_LIKES = 'SORT_BY_LIKES';
export const SORT_BY_RATING = 'SORT_BY_RATING';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const EDIT_MOVIE = 'EDIT_MOVIE';
