export const SET_BASIC_CONTENT = 'SET_BASIC_CONTENT';
export const ADD_CURRENT_MOVIE = 'ADD_CURRENT_MOVIE';
export const CHANGE_COUNT_OF_LIKES = 'CHANGE_COUNT_OF_LIKES';
export const CHANGE_COUNT_OF_STARS = 'CHANGE_COUNT_OF_STARS';
export const FILTER_MOVIE = 'FILTER_MOVIE';
export const SORT_BY_LIKES = 'SORT_BY_LIKES';
export const SORT_BY_RATING = 'SORT_BY_RATING';
